# Generated by Django 6.0.3 on 2026-03-17 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Queue', 'In Queue'), ('Printing', 'Printing'), ('Ready for Pickup', 'Ready for Pickup'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PrintConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('print_type', models.CharField(choices=[('BW', 'Black & White'), ('Color', 'Color')], default='BW', max_length=10)),
                ('sides', models.CharField(choices=[('Single', 'Single Sided'), ('Double', 'Double Sided')], default='Single', max_length=10)),
                ('pages_selection', models.CharField(default='all', help_text="e.g., 'all', '1-5', '1,3,5-7'", max_length=100)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='orders.document')),
            ],
        ),
    ]
