# Generated by Django 6.0.3 on 2026-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_pages',
            field=models.PositiveIntegerField(default=1, help_text='Total pages in the document'),
        ),
    ]
